version: '3.7'
networks:
    dock_net:
        driver: bridge
        ipam:
            driver: default
            config:
            -   subnet: 172.22.0.0/16
services:
    cassandra:
        image: cassandra:latest
        networks:
            dock_net:
                ipv4_address: 172.22.0.100
        ports:
        - 7199:7199
        - 7000:7000
        - 7001:7001
        - 9042:9042
        - 9160:9160
        env_file:
        - cassandra.env
        restart: unless-stopped
    #container_name: cinst1
    cassandra2:
        image: cassandra:latest
        networks:
            dock_net:
                ipv4_address: 172.22.0.117
        env_file:
        - cassandra.env
        restart: unless-stopped
    tinyurl:
        depends_on:
        - cassandra
        - cassandra2
        image: tinyurl
        networks:
        - dock_net
        ports:
        - 8080:8080
        - 8089:8089
        env_file:
        - app.env
        command: |
            /bin/bash -c "
                sleep 60;
            "
